# frozen_string_literal: true

#  == Error message resolution
#
#  Lets errors.add(:field, :some_mo_tag, **interpolation_args) defer tag
#  resolution to display time instead of pre-resolving via .t/.l/.ti/.tl
#  at validation time. Needed because MO's tags live in a flat `mo.*`
#  i18n scope (MO.locale_namespace) that Rails' own ActiveModel::Error
#  message/full_message resolution chain has no path to - no model sets
#  i18n_scope, and generate_message only ever probes
#  <i18n_scope>.errors.* / top-level errors.*, never mo.*.
#
#  resolved_error_message::  A single error's message, resolved via .t
#                             if raw_type is one of MO's tags.
#  resolved_full_message::   Same, formatted like ActiveModel's own
#                             full_message ("Attribute message").
module AbstractModel::ErrorResolution
  # `error.raw_type` is a Symbol in two unrelated cases: an MO tag
  # (deferred here, resolved via .t) or one of Rails' own built-in
  # validation types (:blank, :taken, :invalid, etc., generated by
  # `validates` macros) - the latter must fall through to Rails' own
  # `error.message`/generate_message, which already resolves them
  # correctly; `.t` would look them up in the wrong (mo.*) namespace
  # and never find them. `Symbol#has_translation?` distinguishes the
  # two. `error.options[:message]`, when present, is an explicit
  # override (Rails-native errors.add(:field, :format, message: "..."))
  # and always wins, matching Rails' own generate_message precedence.
  def resolved_error_message(error)
    return error.options[:message] if error.options[:message].is_a?(String)

    raw = error.raw_type
    if raw.is_a?(Symbol) && raw.has_translation?
      raw.t(**error.options.except(:message))
    else
      error.message
    end
  end

  def resolved_full_message(error)
    error.base.errors.full_message(error.attribute,
                                   resolved_error_message(error))
  end
end
