#!/usr/bin/ruby

require File.expand_path('../../config/boot.rb', __FILE__)
require File.expand_path('../../config/environment.rb', __FILE__)

def get_contributions
  result = {}
  for id, login, score in User.connection.select_rows %(
    SELECT id, login, contribution FROM users ORDER BY id
  )
    result["#{id} #{login}"] = score
  end
  return result
end

old_users = get_contributions
SiteData.new.get_all_user_data
new_users = get_contributions

puts "# Differences:"
puts "# id login\told\tnew"
for id, new_val in new_users
  old_val = old_users[id]
  if old_val != new_val
    puts [id, old_val, new_val].join("\t")
  end
end
