#!/bin/bash

if [[ $RAKE_TEST_LOADER != '' ]]; then
  loader=$RAKE_TEST_LOADER
elif [[ $USER == 'velosa' ]]; then
  loader=/Users/velosa/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake/rake_test_loader.rb
else
  loader=/usr/local/lib/ruby/1.9.3/rake/rake_test_loader.rb
fi

/usr/local/bin/ruby -Ilib:test $loader $*
