languages:
  JavaScript: true
  Ruby: true
exclude_paths:
- public/design_test/jquery-1.5.2.min.js
- app/assets/javascripts/bootstrap.js
- app/assets/javascripts/jquery.js
- app/assets/javascripts/jstz.js
- app/assets/javascripts/lightbox.js
