# CodeClimate Configuration
#
# CodeClimate can run two ways:
# newer, "Engine-based" analysis configuration
# older, "Classic" analysis  configuration

################## Engine-Based Configuration ###################

##### engines ####

# CodeClimate will run these "engines" when CodeClimate is triggered.
# For configuration of specific engines, see CodeClimate documentation
#   for that engine.

 engines:
# check Rails apps for security vulnerabilities
  brakeman:
    enabled: true

# helps find security vulnerabilities in Ruby dependencies
  bundler-audit:
    enabled: true

# report similar code blocks over a configurable mass threshold
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript

# linting, complexity analysis, & style checking for EcmaScript/JavaScript
  eslint:
    enabled: true

# case-sensitive search for the following strings: TODO, FIXME, HACK, XXX, BUG
# Can be configured to search for any strings
  fixme:
    enabled: true
# We use "xxx" in numerous places, e.g., theme templates
    checks:
      XXX:
        enabled: false

# markdown style check
  markdownlint:
    enabled: true

# style and quality checks for Ruby code
# configuration details are in .rubocop.yml files, rather than here.
  rubocop:
    enabled: true

# scss style checker
  scss-lint:
    enabled: true

#### exclude_paths ####

# A list of file "patterns" completely excluded from analysis
# Each pattern is either: filenames relative to the project root,
#   or shell-style globs relative to the project root.
# Patterns other than named paths starting at root
#   must be enclosed in quotes, e.g.: "**.rb", "**/subdir/".
# Patterns can be negated by prefixing them with a !.
#   A negated pattern will include the matched files for analysis,
#   even if they were excluded by a previous pattern.

exclude_paths:
- app/assets/javascripts/bootstrap.js
- app/assets/javascripts/jquery.js
- app/assets/javascripts/jstz.js
- app/assets/javascripts/lightbox.js
# This file causes a CodeClimate error in the Duplication engine
- app/classes/query/modules/serialization.rb
# Prevent analysis of migrations
- db/
- log/
- public/design_test/jquery-1.5.2.min.js
- tmp/


#### ratings ####

# Files which get a letter grade (A-F) and are included in overall
# CodeClimate numerical score
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.js"
  - "**.md"
  - "**.rake"
  - "**.rb"
  - "**.scss"

######################## Classic configuration ##########################
# Kept for convenience in case we decide to drop Engine-Based configuration
# languages:
#  JavaScript: true
#  Ruby: true
# exclude_paths:
# - public/design_test/jquery-1.5.2.min.js
# - app/assets/javascripts/bootstrap.js
# - app/assets/javascripts/jquery.js
# - app/assets/javascripts/jstz.js
# - app/assets/javascripts/lightbox.js
# - app/classes/query/modules/serialization.rb

################## CodeClimate's "inferred .codeclimate.yml" ##################
# Codeclimate generated this based on the Classic configuration above
#
# engines:
#   brakeman:
#     enabled: true
#   bundler-audit:
#     enabled: true
#   duplication:
#     enabled: true
#     config:
#       languages:
#       - ruby
#       - javascript
#       - python
#       - php
#   eslint:
#     enabled: true
#   fixme:
#     enabled: true
#   rubocop:
#     enabled: true
# ratings:
#   paths:
#   - Gemfile.lock
#   - "**.erb"
#   - "**.haml"
#   - "**.rb"
#   - "**.rhtml"
#   - "**.slim"
#   - "**.inc"
#   - "**.js"
#   - "**.jsx"
#   - "**.module"
#   - "**.php"
#   - "**.py"
#  exclude_paths:
#  - public/design_test/jquery-1.5.2.min.js
#  - app/assets/javascripts/bootstrap.js"
# 	"---
# engines:
#   brakeman:
#     enabled: true
#   bundler-audit:
#     enabled: true
#   duplication:
#     enabled: true
#     config:
#       languages:
#       - ruby
#       - javascript
#       - python
#       - php
#   eslint:
#     enabled: true
#   fixme:
#     enabled: true
#   rubocop:
#     enabled: true
# ratings:
#   paths:
#   - Gemfile.lock
#   - "**.erb"
#   - "**.haml"
#   - "**.rb"
#   - "**.rhtml"
#   - "**.slim"
#   - "**.inc"
#   - "**.js"
#   - "**.jsx"
#   - "**.module"
#   - "**.php"
#   - "**.py"
#  exclude_paths:
#  - public/design_test/jquery-1.5.2.min.js
#  - app/assets/javascripts/bootstrap.js"

