inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

# ------------------------------------------------------------------------------
# Updating RuboCop
#
# *** Update The Codeclimate Channel When Updating Rubocop
# See docs.codeclimate.com/docs/rubocop#section-using-rubocop-s-newer-versions
# Use the highest available channel that's compatible with the RuboCop version.
# .codeclimate.yml specifies the RuboCop version ('channel') used
# by Code Climate, which can be different than the version in Gemfile.lock
#
# *** Re-generate the RuboCop auto-configuration todo list
# at least run rubocop --regenerate-todo and commit changes
# optionally follow other suggestions at
# https://docs.rubocop.org/rubocop/configuration.html#automatically-generated-configuration
#
# ------------------------------------------------------------------------------

# RuboCop configuration
# Uses Rubcop's default configuration, except as specified below
# For more info, see https://docs.rubocop.org/rubocop/configuration.html

AllCops:
  # See https://docs.rubocop.org/rubocop/versioning.html#pending-cops
  NewCops: disable

  ########################### Excluded files ###################################
  # Completely ignore the following
  Exclude:
    - .codeclimate.yml
    - app/assets/javascripts/bootstrap.js
    - app/assets/javascripts/jquery.js
    - app/assets/javascripts/jstz.js
    - app/assets/javascripts/lightbox.js
    # old API is frozen
    - app/classes/api.rb
    - "app/classes/api/**/*"
    - app/controllers/api_controller.rb
    - app/helpers/api_helper.rb
    - "app/views/api/**/*"
    - test/controllers/api_controller_test.rb
    - test/models/api_test.rb
    - "db/**/*"
    - "log/**/*"
    - public/design_test/jquery-1.5.2.min.js
    # We need not check these scripts, and some of them cause Rubocop errors
    - "script/old/**/*"
    # not Ruby
    - script/perf_monitor
    - "tmp/**/*"

# ------------------------------------------------------------------------------

#####  Individual Cops

# Use RuboCop's default configuration, except as specified below
# NOTE: pending cops have no default, so it must be specified

# Rubocop supports multiple options and MO uses a non-default
# Default: align "end" with **start of the line** that includes "begin"
# MO align with "begin". This is how we've almost always done it.
# And it's consistent with Layout/EndAlignment for other keywords.
Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin

# Rubocop supports multiple options and MO uses a non-default
Layout/DotPosition:
  EnforcedStyle: trailing

# Repeat the default because Codeclimate ignores it as of 2019-07-09
Layout/HashAlignment:
  EnforcedColonStyle: key

# Rubocop supports multiple options and MO uses a non-default
Layout/LineLength:
  # RuboCop default is 120 as of 0.84
  Max: 80

Metrics/AbcSize:
  # Can we try relaxing this one?  Even short simple methods sometimes exceed
  # 15 or 16.  Simplifying them further just forces us to make tons of tiny
  # trivial methods with really cumbersome names, without actually making
  # the code any better.
  # Max: 15
  Max: 20
  Exclude:
    # This Cop makes less sense in tests, we regularly ignore it.
    - "test//**/*"

Metrics/BlockLength:
  Exclude:
    # This Cop makes less sense in tests, we regularly ignore it.
    - "test//**/*"

Metrics/ClassLength:
  # Relaxed metrics based on CodeClimages default .rubocop.yml
  # Max: 100
  Max: 250
  Exclude:
    # This Cop makes less sense in tests, we regularly ignore it.
    - "test//**/*"

Metrics/CyclomaticComplexity:
  Exclude:
    # This Cop makes less sense in tests, we regularly ignore it.
    - "test//**/*"

Metrics/MethodLength:
  # Relaxed metrics based on CodeClimages default .rubocop.yml
  # Max: 10
  Max: 30
  Exclude:
    # This Cop makes less sense in tests, we regularly ignore it.
    - "test//**/*"

Metrics/ModuleLength:
  # Relaxed metrics based on CodeClimages default .rubocop.yml
  # Max: 100
  Max: 250
  Exclude:
    # This Cop makes less sense in tests, we regularly ignore it.
    - "test//**/*"

Metrics/PerceivedComplexity:
  Exclude:
    # This Cop makes less sense in tests, we regularly ignore it.
    - "test//**/*"

# Disable because it does not work with Unicode in Ruby 2.4
# Cop supports --auto-correct.
Performance/Casecmp:
  Enabled: false

Performance/RegexpMatch:
  # Autocorrect changes "something.match(regexp)" to "something.match?(regexp)".
  # The latter throws an error when something == nil:
  #   undefined method `match?' for nil:NilClass
  # So manually correct to: regexp.match?(something)
  AutoCorrect: false

Performance/StringInclude:
  # "This cop’s offenses are not safe to auto-correct if a receiver is nil."
  Enabled: false

# Make autocorrect saf(er) by whitelisting our find_by methods
Rails/DynamicFindBy:
  AllowedMethods: find_by_sql, find_by_code_with_wildcards, find_by_name_with_wildcards, find_by_name_or_reverse_name, find_by_scientific_name_with_wildcards, find_by_title_with_wildcards, find_by_title_with_wildcards
  AutoCorrect: true

# MO uses HABTM extensively; RuboCop prefers the newer has_many through
# Switching would require a migration process, detailed here:
# http://chrisrolle.com/en/blog/migration-path-from-habtm-to-has_many-through
# It's not worth the effort
Rails/HasAndBelongsToMany:
  Enabled: false

# Can be unsafe depending on eager_load vs pre_load
# https://docs.rubocop.org/rubocop-rails/cops_rails.html#railswhereexists
Rails/WhereExists:
  Enabled: false

Style/AccessorGrouping:
  # Disabled. See discussion at
  # https://github.com/MushroomObserver/mushroom-observer/pull/988
  Enabled: false
  # The follow in case we re-enable the cop
  # Exclude files that individually comment accessors
  # else Rubocop concatenates the accessors and comments on a single line.
  # Disabling Style/AccessorGrouping around the accessors doesn't
  # work in this context because Rubocop v1.30.0 generates a
  # Style/EmptyLinesAroundAttributeAccessor offense
  # See https://github.com/rubocop/rubocop/issues/10693
  Exclude:
    - "app/classes/country_counter.rb"
    - "app/classes/gmaps.rb"
    - "app/classes/mo_paginator.rb"

# Allow non-ascii characters in comments; we need to use accented chars
Style/AsciiComments:
  Enabled: false

# Repeat the RuboCop default because CodeClimate silently overrides it
# Is this still true? JDC 2020-08-17
Style/DateTime:
  Enabled: false

# Rubocop does not enable this cop by defaul
# MO uses parentheses
Style/MethodCallWithArgsParentheses:
  Enabled: true

# Repeat the RuboCop defaults because Codeclimate silently overrides them
# Is that still true? JDC 2020-08-17?
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "()"
    "%i": "[]"
    "%I": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"

# I can't figure out how to get exploded to work with API.
Style/RaiseArgs:
  EnforcedStyle: compact

# Rubocop supports multiple options and MO uses a non-default
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Rubocop supports multiple options and MO uses a non-default
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# MO uses [] not %i() or %I()
Style/SymbolArray:
  EnforcedStyle: brackets

# We skip validations all the time.  I'm tired of disabling this cop.
Rails/SkipsModelValidations:
  Enabled: false
