# Local RuboCop configuration

inherit_from: # see https://docs.rubocop.org/rubocop/1.72/configuration.html#inheriting-from-another-configuration-file-in-the-project
  - .rubocop_shared.yml
  - .rubocop_todo.yml # comes last to override above shared files
inherit_mode:
  merge:
    - Exclude

# NOTE: 20250222 jdc
# RuboCop 1.72 uses `plugins:` (not` `require:`) to load plugin extensions
# See https://docs.rubocop.org/rubocop/1.72/extensions.html
plugins:
  - rubocop-performance
  - rubocop-rails

# ------------------------------------------------------------------------------
# Updating RuboCop
#
# *** Update The Codeclimate Channel When Updating Rubocop
# See docs.codeclimate.com/docs/rubocop#section-using-rubocop-s-newer-versions
# Use the highest available channel that's compatible with the RuboCop version.
# Available channels: https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop
# .codeclimate.yml specifies the RuboCop version ('channel') used
# by Code Climate, which can be different than the version in Gemfile.lock
#
# *** Re-generate the RuboCop auto-configuration todo list
# at least run rubocop --regenerate-todo and commit changes
# optionally follow other suggestions at
# https://docs.rubocop.org/rubocop/configuration.html#automatically-generated-configuration
