# This is the file used by CodeClimate GitHub CI App to run RuboCop.

# NOTE: 20250222 jdc
# This file uses `require` instead of `plugins:` See NOTE 20250219 below.
# If CodeClimate adds a channel > rubocop-1-56-3 which uses `plugins:`
# - Update .codeclimate.yml to use that new channel
# - Update .codeclimate.yml to remove plugins: rubocop: config:
# - Delete this file
# - Consider merging .rubocop_shared.yml into .rubocop.yml

inherit_from:
  - .rubocop_shared.yml
  - .rubocop_todo.yml # comes last to override above shared files
inherit_mode:
  merge:
    - Exclude

# NOTE: 20250219 jdc
# Use `require:` because CodeClimate does not support `plugins:`
# Example: https://codeclimate.com/github/MushroomObserver/mushroom-observer/builds/11148
require:
  - rubocop-performance
  - rubocop-rails
