source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 3.0.10'
gem 'mysql2'
gem 'activerecord-mysql2-adapter'
gem 'mysql' # To keep rake happy for some reason
gem 'test-unit'
gem 'RedCloth'
# gem 'sparql', '> 1'
gem 'i18n'
gem 'acts_as_versioned' # , '0.2.3'
gem 'enum_column3'
gem 'blankslate'
gem 'browser'
gem 'ruby-rtf'
