# frozen_string_literal: true

# Form for creating an Occurrence by selecting observations.
# Renders a grid of observation matrix boxes with Include
# checkboxes and Primary radio buttons.
#
# Uses the `Occurrence` AR model directly (rather than a separate
# form object), following the same pattern as `ObservationForm`.
# `Occurrence#observation_ids` is auto-generated by the
# `has_many :observations` association; `primary_observation_id`
# is a column. Both can be addressed directly with
# `field(:observation_ids)` / `field(:primary_observation_id)`.
class Components::OccurrenceForm < Components::ApplicationForm
  def initialize(source_obs:, recent_observations:, user:, **)
    @source_obs = source_obs
    @recent_observations = recent_observations
    @user = user
    super(Occurrence.new(primary_observation: source_obs), **)
  end

  def view_template
    render_source_obs_id_hidden
    render_observation_grid
    submit(:create_occurrence_submit.l, center: true)
  end

  def form_action
    occurrences_path
  end

  private

  # Flat `observation_id` (form context, not an Occurrence attribute) so
  # the controller can identify the source obs on POST — needed for the
  # `redirect back to /occurrences/new?observation_id=X` error path.
  def render_source_obs_id_hidden
    hidden_field("observation_id", value: @source_obs.id)
  end

  def render_observation_grid
    all_obs = [@source_obs] + @recent_observations
    ul(
      class: "row list-unstyled mt-3",
      data: {
        controller: "matrix-table occurrence-form",
        action: "resize@window->matrix-table#rearrange",
        "occurrence-form-fallback-value": "source"
      }
    ) do
      all_obs.each { |obs| render_obs_box(obs) }
    end
  end

  def render_obs_box(obs)
    MatrixBox(user: @user, object: obs, votes: false) do
      render_obs_controls(obs)
    end
  end

  def render_obs_controls(obs)
    if obs == @source_obs
      render_source_controls(obs)
    else
      render_recent_controls(obs)
    end
  end

  # The source obs is always included — render a hidden array-element
  # so `occurrence[observation_ids][]=source.id` always submits, then
  # show the "Source" label and the (checked) primary radio.
  def render_source_controls(obs)
    hidden_field("occurrence[observation_ids][]", value: obs.id)
    strong { plain(:create_occurrence_source.l) }
    render_primary_radio(obs)
  end

  def render_recent_controls(obs)
    render_include_checkbox(obs)
    render_primary_radio(obs)
    render_occurrence_warning(obs)
  end

  # `cb.option(value)` renders a single `<input type="checkbox"
  # name="occurrence[observation_ids][]" value="...">` wrapped in
  # MO's `.checkbox` div. The block becomes the label text.
  def render_include_checkbox(obs)
    checkbox_field(:observation_ids,
                   label: false, wrap_class: "my-0",
                   data: { action: "occurrence-form#includeToggled" }) do |cb|
      cb.option(obs.id) { "Include" }
    end
  end

  # All radio rows render against the same `primary_observation_id`
  # field; only the option whose value matches `field.value`
  # (i.e. the source on initial render) gets `checked`.
  def render_primary_radio(obs)
    radio_field(:primary_observation_id,
                [obs.id, :create_occurrence_primary.l],
                wrap_class: "my-0",
                data: primary_radio_data(obs))
  end

  def primary_radio_data(obs)
    data = { action: "occurrence-form#primarySelected" }
    data[:"occurrence-form-target"] = "sourceRadio" if obs == @source_obs
    data
  end

  def render_occurrence_warning(obs)
    fs = obs.field_slip
    if fs
      render_field_slip_link(fs)
    elsif obs.occurrence&.observations&.many?
      render_multi_occurrence_link(obs)
    end
  end

  def render_field_slip_link(field_slip)
    br
    small do
      a(href: field_slip_path(field_slip)) do
        plain("Field Slip: #{field_slip.code}")
      end
    end
  end

  def render_multi_occurrence_link(obs)
    br
    a(href: occurrence_path(obs.occurrence_id)) do
      span(class: "glyphicon glyphicon-th-large")
      plain(" ")
      plain(:in_existing_occurrence.l)
    end
  end
end
