From: news@mushroomobserver.org
Reply-To: no-reply@mushroomobserver.org
To: rolf@collectivesource.com
Bcc: nathan@collectivesource.com
Subject: [MO] Comment about Fungi sp. (1)
Mime-Version: 1.0
Content-Type: text/html; charset=utf-8
<html>
<head>
<title>Mushroom Observer: Comment about Fungi sp. (1)</title>
</head>
<body topmargin=0 leftmargin=0 rightmargin=0 bottommargin=0><br/>
<div class="textile"><h2><strong>Comment Response</strong></h2>
	<p>The following comment was posted on the Mushroom Observer website in response to your comment regarding the Observation <u><b><i>Fungi sp.</i></b> (1)</u>:</p></div>
<div class="textile"><p><strong>Created:</strong> 2006-03-02 21:16:00<br/><strong>By:</strong> Tricky Dick (dick)<br/><strong>Summary:</strong> Let&#8217;s <em>try</em> a more &#8220;complicated&#8221; comment.<br/><strong>Comment:</strong></p></div>
<div style='margin-left:20px; margin-right:20px; padding-left:20px; padding-right:20px; padding-top:10px; padding-bottom:10px; border:1px dotted; background:#E0E0E0; color:#000000;'>
<div class="textile"><p>With <em>Agaricus campestris</em> links and <strong>boldface</strong> and<br/>4&#215;4 other weird&#8482; !image 2! stuff.</p>
	<p>Just to test html_to_ascii&#8230;  -A&amp;P</p></div>
</div>
<div class="textile"><p><strong>Please do not reply to this email!</strong> Use the link below to respond via your own public comment.<br/> Here are some handy links:</p></div>
<ul type=none>
<li>Show this Observation: <a href="http://localhost:3000/observer/show_observation/1">http://localhost:3000/observer/show_observation/1</a></li>
<li>Post a comment: <a href="http://localhost:3000/comment/add_comment?id=1&type=Observation">http://localhost:3000/comment/add_comment?id=1&type=Observation</a></li>
<li>I'm not interested in this Observation: <a href="http://localhost:3000/interest/set_interest?id=1&type=Observation&user=1">http://localhost:3000/interest/set_interest?id=1&type=Observation&user=1</a></li>
<li>Stop sending me email like this: <a href="http://localhost:3000/account/no_email_comments_response/1">http://localhost:3000/account/no_email_comments_response/1</a></li>
<li>Change your preferences: <a href="http://localhost:3000/account/prefs/1">http://localhost:3000/account/prefs/1</a></li>
<li>Latest changes at Mushroom Observer: <a href="http://localhost:3000">http://localhost:3000</a></li>
</ul>
<div class="textile"><p>If you feel this user is abusing this service please forward this entire email message to: webmaster@mushroomobserver.org</p></div>
<br/>
</body>
</html>
