From: news@mushroomobserver.org
Reply-To: rolf@collectivesource.com
To: mary@collectivesource.com
Bcc: nathan@collectivesource.com
Subject: [MO] Comment about Fungi sp. (1)
Mime-Version: 1.0
Content-Type: text/html; charset=utf-8
<html>
<head>
<title>Mushroom Observer: Comment about Fungi sp. (1)</title>
</head>
<body topmargin=0 leftmargin=0 rightmargin=0 bottommargin=0><br/>
<div class="textile"><h2><strong>Comment on Your Observation</strong></h2>
	<p>The following comment was posted on the Mushroom Observer website regarding your Observation <u><b><i>Fungi sp.</i></b> (1)</u>:</p></div>
<div class="textile"><p><strong>Created:</strong> 2006-03-02 21:14:00<br/><strong>By:</strong> Rolf Singer (rolf)<br/><strong>Summary:</strong> A comment on minimal unknown<br/><strong>Comment:</strong></p></div>
<div style='margin-left:20px; margin-right:20px; padding-left:20px; padding-right:20px; padding-top:10px; padding-bottom:10px; border:1px dotted; background:#E0E0E0; color:#000000;'>
<div class="textile"><p>Wow!  That&#8217;s really cool</p></div>
</div>
<div class="textile"><p>It is entirely up to you whether you want to reply to Rolf Singer (rolf@collectivesource.com) by replying directly to this email.<br/> Here are some handy links:</p></div>
<ul type=none>
<li>Show this Observation: <a href="http://localhost:3000/observer/show_observation/1">http://localhost:3000/observer/show_observation/1</a></li>
<li>Post a comment: <a href="http://localhost:3000/comment/add_comment?id=1&type=Observation">http://localhost:3000/comment/add_comment?id=1&type=Observation</a></li>
<li>I'm not interested in this Observation: <a href="http://localhost:3000/interest/set_interest?id=1&type=Observation&user=2&state=-1">http://localhost:3000/interest/set_interest?id=1&type=Observation&user=2&state=-1</a></li>
<li>Stop sending me email like this: <a href="http://localhost:3000/account/no_email_comments_owner/2">http://localhost:3000/account/no_email_comments_owner/2</a></li>
<li>Change your preferences: <a href="http://localhost:3000/account/prefs/2">http://localhost:3000/account/prefs/2</a></li>
<li>Latest changes at Mushroom Observer: <a href="http://localhost:3000">http://localhost:3000</a></li>
</ul>
<div class="textile"><p>If you feel this user is abusing this service please forward this entire email message to: webmaster@mushroomobserver.org</p></div>
<br/>
</body>
</html>
