From: news@mushroomobserver.org
Reply-To: mary@collectivesource.com
To: rolf@collectivesource.com
Bcc: nathan@collectivesource.com
Subject: [MO] Commercial Inquiry about Image #3
Mime-Version: 1.0
Content-Type: text/html; charset=utf-8
<html>
<head>
<title>Mushroom Observer: Commercial Inquiry about Image #3</title>
</head>
<body topmargin=0 leftmargin=0 rightmargin=0 bottommargin=0><br/>
<div class="textile"><h2><strong>Commercial Inquiry</strong></h2>
	<p>Mary Newbie (mary@collectivesource.com) asked the Mushroom Observer website to forward the following commercial inquiry to you about your image Image #3:</p></div>
<div style='margin-left:20px; margin-right:20px; padding-left:20px; padding-right:20px; padding-top:10px; padding-bottom:10px; border:1px dotted; background:#E0E0E0; color:#000000;'>
<div class="textile"><p>Did test_commercial_inquiry work?</p></div>
</div>
<div class="textile"><p>It is entirely up to you whether you want to reply to Mary Newbie (mary@collectivesource.com) by replying directly to this email.<br/> Here are some handy links:</p></div>
<ul type=none>
<li>Show this Image: <a href="http://localhost:3000/image/show_image/3">http://localhost:3000/image/show_image/3</a></li>
<li>Stop sending me email like this: <a href="http://localhost:3000/account/no_email_general_commercial/1">http://localhost:3000/account/no_email_general_commercial/1</a></li>
<li>Change your preferences: <a href="http://localhost:3000/account/prefs/1">http://localhost:3000/account/prefs/1</a></li>
<li>Latest changes at Mushroom Observer: <a href="http://localhost:3000">http://localhost:3000</a></li>
</ul>
<div class="textile"><p>If you feel this user is abusing this service please forward this entire email message to: webmaster@mushroomobserver.org</p></div>
<br/>
</body>
</html>
