From: news@mushroomobserver.org
Reply-To: no-reply@mushroomobserver.org
To: mary@collectivesource.com
Bcc: nathan@collectivesource.com
Subject: Consensus rejected Agaricus campestris L. in favor of Coprinus comatus (O.F. Mull.) Pers.
Mime-Version: 1.0
Content-Type: text/html; charset=utf-8

<html>
<head>
  <title>Mushroom Observer: Consensus Changed for Observation #3</title>
</head>
<body topmargin=0 leftmargin=0 rightmargin=0 bottommargin=0><br/>
<p>Consensus changed for observation #3:</p>
<p><strong>Old Name:</strong> <a href="http://localhost:3000/name/show_name/3"><b><i>Agaricus campestris</i></b> L.</a><br/><strong>New Name:</strong> <a href="http://localhost:3000/name/show_name/2"><b><i>Coprinus comatus</i></b> (O.F. Müll.) Pers.</a><br/><strong>Time:</strong> 2007-02-27 20:20:00<br/><strong>By:</strong> Tricky Dick (dick)</p>
<p>Here are some links you may find useful:</p>
<ul type=none>
  
    <li>Show this observation: <a href="http://localhost:3000/3">http://localhost:3000/3</a></li>
  
    <li>Post comment on this observation: <a href="http://localhost:3000/comment/add_comment?id=3&type=Observation">http://localhost:3000/comment/add_comment?id=3&type=Observation</a></li>
  
    <li>I'm not interested in this observation: <a href="http://localhost:3000/interest/set_interest?id=3&type=Observation&user=2">http://localhost:3000/interest/set_interest?id=3&type=Observation&user=2</a></li>
  
    <li>Stop sending me these notifications: <a href="http://localhost:3000/account/no_consensus_change_email/2">http://localhost:3000/account/no_consensus_change_email/2</a></li>
  
    <li>Change your account preferences: <a href="http://localhost:3000/account/prefs/2">http://localhost:3000/account/prefs/2</a></li>
  
    <li>Latest changes at Mushroom Observer: <a href="http://localhost:3000">http://localhost:3000</a></li>
  
</ul>
<br/>
</body>
</html>
