From: news@mushroomobserver.org
Reply-To: no-reply@mushroomobserver.org
To: mary@collectivesource.com
Bcc: nathan@collectivesource.com
Subject: [MO] Albion, Mendocino Co., California, USA Has Been Changed
Mime-Version: 1.0
Content-Type: text/html; charset=utf-8
<html>
<head>
<title>Mushroom Observer: Albion, Mendocino Co., California, USA Has Been Changed</title>
</head>
<body topmargin=0 leftmargin=0 rightmargin=0 bottommargin=0><br/>
<div class="textile"><h2><strong>Location was Changed</strong></h2>
	<p>There were change(s) made to the Location <u>Albion, Mendocino Co., California, <span class="caps">USA</span> (1)</u>:</p></div>
<div class="textile"><p><strong>Time:</strong> 2007-12-27 06:41:20<br/><strong>By:</strong> Tricky Dick (dick)</p></div>
<div class="textile"><p><strong>North edge changed to:</strong> 39.32<br/><strong>South edge changed to:</strong> 39.21<br/><strong>East edge changed to:</strong> -123.74<br/><strong>West edge changed to:</strong> -123.82</p></div>
<div class="textile"><p><strong>Notes changed to:</strong></p></div>
<div style='margin-left:20px; margin-right:20px; padding-left:20px; padding-right:20px; padding-top:10px; padding-bottom:10px; border:1px dotted; background:#E0E0E0; color:#000000;'>
<div class="textile"><p>Here are some new notes to play with.</p></div>
</div>
<div class="textile"><p>Here are some handy links:</p></div>
<ul type=none>
<li>Show this Location: <a href="http://localhost:3000/location/show_location/1">http://localhost:3000/location/show_location/1</a></li>
<li>I'm not interested in this Location: <a href="http://localhost:3000/interest/set_interest?id=1&type=Location&user=2">http://localhost:3000/interest/set_interest?id=1&type=Location&user=2</a></li>
<li>Stop sending me email like this: <a href="http://localhost:3000/account/no_email_locations_editor/2">http://localhost:3000/account/no_email_locations_editor/2</a></li>
<li>Change your preferences: <a href="http://localhost:3000/account/prefs/2">http://localhost:3000/account/prefs/2</a></li>
<li>Latest changes at Mushroom Observer: <a href="http://localhost:3000">http://localhost:3000</a></li>
</ul>
<br/>
</body>
</html>
