From: news@localhost
Reply-To: no-reply@localhost
To: mary@collectivesource.com
Subject: [MO] Petigera Has Been Changed
Mime-Version: 1.0
Content-Type: text/html; charset=utf-8
<html>
<head>
<title>Mushroom Observer: Petigera Has Been Changed</title>
</head>
<body topmargin=0 leftmargin=0 rightmargin=0 bottommargin=0><br/>
<div class="textile"><h2><strong>Name was Changed</strong></h2>
	<p>There were change(s) made to the Name <u><i>Petigera</i> (40)</u>:</p></div>
<div class="textile"><p><strong>Time:</strong> 2009-01-02 01:01:01<br/><strong>By:</strong> Tricky Dick (dick)</p></div>
<div class="textile"><p><strong>Name changed to:</strong> Peltigera<br/><strong>Author changed to:</strong> (Old) New Auth.<br/><strong>Citation changed to:</strong> Ye Auld Manual of Lichenes, 1800.<br/><strong>Rank changed to:</strong> Genus<br/><strong>License changed to:</strong> Creative Commons Non-commercial v3.0<br/><strong>Status changed to:</strong> vetted<br/><strong>Status changed to:</strong> Accepted</p></div>
<div class="textile"><p><strong>Taxonomic classification changed to:</strong></p></div>
<div style='margin-left:20px; margin-right:20px; padding-left:20px; padding-right:20px; padding-top:10px; padding-bottom:10px; border:1px dotted; background:#E0E0E0; color:#000000;'>
<div class="textile"><p>Kingdom: <em>Fungi</em><br/>Phylum: <em>Ascomycota</em><br/>Class: <em>Euascomycetes</em><br/>Order: <em>Lecanorales</em><br/>Family: <em>Peltigeraceae</em></p></div>
</div>
<div class="textile"><p><strong>General Description changed to:</strong></p></div>
<div style='margin-left:20px; margin-right:20px; padding-left:20px; padding-right:20px; padding-top:10px; padding-bottom:10px; border:1px dotted; background:#E0E0E0; color:#000000;'>
<div class="textile"><p>Broad leafy lichens with soft, felty undersurface, generally with conspicuous veins and rhizines.</p></div>
</div>
<div class="textile"><p><strong>Diagnostic Description changed to:</strong></p></div>
<div style='margin-left:20px; margin-right:20px; padding-left:20px; padding-right:20px; padding-top:10px; padding-bottom:10px; border:1px dotted; background:#E0E0E0; color:#000000;'>
<div class="textile"><p>Large foliose lichens with either green algae or cyanobacterial photopartners; apothecia on the upper surface of the lobes; soredia, isidia, and/or lobules often present; undersurface ecorticate, often with raised veins and rhizines; upper surface smooth to often tomentose.</p></div>
</div>
<div class="textile"><p><strong>Distribution changed to:</strong></p></div>
<div style='margin-left:20px; margin-right:20px; padding-left:20px; padding-right:20px; padding-top:10px; padding-bottom:10px; border:1px dotted; background:#E0E0E0; color:#000000;'>
<div class="textile"><p>Cosmopolitan.</p></div>
</div>
<div class="textile"><p><strong>Habitat changed to:</strong></p></div>
<div style='margin-left:20px; margin-right:20px; padding-left:20px; padding-right:20px; padding-top:10px; padding-bottom:10px; border:1px dotted; background:#E0E0E0; color:#000000;'>
<div class="textile"><p>Mostly found growing with or over mosses, on soil, base of tree trunks, logs and rocks, rarely on trees or limbs.</p></div>
</div>
<div class="textile"><p><strong>Look Alikes changed to:</strong></p></div>
<div style='margin-left:20px; margin-right:20px; padding-left:20px; padding-right:20px; padding-top:10px; padding-bottom:10px; border:1px dotted; background:#E0E0E0; color:#000000;'>
<div class="textile"><p>Other felt lichens such as <em>Lobaria</em>, <em>Pseudocyphellaria</em>, <em>Sticta</em> and <em>Nephroma</em> look superficially similar but never have well-developed veins or rhizines underneath.</p></div>
</div>
<div class="textile"><p><strong>Uses changed to:</strong></p></div>
<div style='margin-left:20px; margin-right:20px; padding-left:20px; padding-right:20px; padding-top:10px; padding-bottom:10px; border:1px dotted; background:#E0E0E0; color:#000000;'>
<div class="textile"><p>Good for making birds nests&#8230; if you&#8217;re a bird.</p></div>
</div>
<div class="textile"><p>Here are some handy links:</p></div>
<ul type=none>
<li>Show this Name: <a href="http://localhost:3000/name/show_name/40">http://localhost:3000/name/show_name/40</a></li>
<li>I'm not interested in this Name: <a href="http://localhost:3000/interest/set_interest?id=40&type=Name&user=2&state=-1">http://localhost:3000/interest/set_interest?id=40&type=Name&user=2&state=-1</a></li>
<li>Stop sending me email like this: <a href="http://localhost:3000/account/no_email_names_all/2">http://localhost:3000/account/no_email_names_all/2</a></li>
<li>Change your preferences: <a href="http://localhost:3000/account/prefs/2">http://localhost:3000/account/prefs/2</a></li>
<li>Latest changes at Mushroom Observer: <a href="http://localhost:3000">http://localhost:3000</a></li>
</ul>
<br/>
</body>
</html>
