From: news@mushroomobserver.org
Reply-To: no-reply@mushroomobserver.org
To: mary@collectivesource.com
Bcc: nathan@collectivesource.com
Subject: [MO] Naming Notification
Mime-Version: 1.0
Content-Type: text/html; charset=utf-8
<html>
<head>
<title>Mushroom Observer: Naming Notification</title>
</head>
<body topmargin=0 leftmargin=0 rightmargin=0 bottommargin=0><br/>
<div class="textile"><h2><strong>Tracking Alert</strong></h2>
	<p>An <a href="http://localhost:3000/4">Observation</a> on the Mushroom Observer website has been given the name <a href="http://localhost:3000/name/show_name/3"><b><i>Agaricus campestris</i></b> L.</a>, which you are currently tracking.  You can contact either the observer or the identifier by going to the appropriate link below and clicking the email link near the top of the page.</p></div>
<div class="textile"><p><strong>Observer:</strong> <a href="http://localhost:3000/observer/observer/show_user/1">Rolf Singer</a><br/><strong>Identifier:</strong> <a href="http://localhost:3000/observer/observer/show_user/1">Rolf Singer</a><br/><strong>No herbarium specimen</strong><br/><strong>Image count:</strong> 1</p></div>
<div class="textile"><p>Here are some handy links:</p></div>
<ul type=none>
<li>Show this Observation: <a href="http://localhost:3000/4">http://localhost:3000/4</a></li>
<li>Show observer's profile: <a href="http://localhost:3000/observer/observer/show_user/1">http://localhost:3000/observer/observer/show_user/1</a></li>
<li>Disable tracking for this Name: <a href="http://localhost:3000/name/email_tracking/3">http://localhost:3000/name/email_tracking/3</a></li>
<li>Review your notifications: <a href="http://localhost:3000/interest/list_interests">http://localhost:3000/interest/list_interests</a></li>
<li>Latest changes at Mushroom Observer: <a href="http://localhost:3000">http://localhost:3000</a></li>
</ul>
<div class="textile"><p>If you feel this user is abusing this service please forward this entire email message to: webmaster@mushroomobserver.org</p></div>
<br/>
</body>
</html>
