From: accounts@mushroomobserver.org
To: mary@collectivesource.com
Bcc: mo@collectivesource.com
Subject: [MO] Email Verification
Mime-Version: 1.0
Content-Type: text/html; charset=utf-8
<html>
<head>
<title>Mushroom Observer: Email Verification</title>
</head>
<body topmargin=0 leftmargin=0 rightmargin=0 bottommargin=0><br/>
<div class="textile"><h2><strong>Hello mary</strong></h2>
	<p>Please click on the following link to verify that you received this email and activate your Mushroom Observer account:</p>
	<p><a href="http://localhost:3000/account/verify/2">http://localhost:3000/account/verify/2</a></p></div>
<br/>
</body>
</html>
