# SENSITIVE INFORMATION: This file should not be checked into subversion

# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Get the fast C bindings:
#   gem install mysql2
#   (on OS X: gem install mysql -- --include=/usr/local/lib)
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

shared:
  adapter: mysql2
  # Default (works for MacOS X)
  # socket: /tmp/mysql.sock
  # For Ubuntu/Debian
  socket: /var/run/mysqld/mysqld.sock
  # For Fedora
  # socket: /var/lib/mysql/mysql.sock
  # Connect on a TCP socket.  If omitted, the adapter will connect on the
  # domain socket given by socket instead.
  #host: localhost
  #port: 3306
  # For mysql >= 5.7.5
  # Do not require SELECT list to include ORDER BY columns in DISTINCT queries,
  # And do not not require ORDER BY to include the DISTINCT column.
  variables:
    sql_mode: TRADITIONAL

development:
  database: mo_development
  username: mo
  password: mo

# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
test:
  database: mo_test
  username: mo
  password: mo

production:
  database: mo_development
  username: mo
  password: mo
