# frozen_string_literal: true

require_relative("boot")

# To load all of Rails:
# require("rails/rails")

# To choose what Rails frameworks to load, and skip others:
# NOTE: Be sure this list reflects the same choices made in the Gemfile
require("rails") # NOTE: not "rails/rails"
require("active_model/railtie")
require("active_job/railtie")
require("active_record/railtie")
# require("active_storage/engine")
require("action_controller/railtie")
require("action_mailer/railtie")
# require("action_mailbox/engine")
# require("action_text/engine")
require("action_view/railtie")
require("action_cable/engine")
require("sprockets/railtie")
require("rails/test_unit/railtie")

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module MushroomObserver
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those
    # specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Every setting from new_framework_defaults_7_0.rb/_7_1.rb/_7_2.rb has
    # been individually audited and enabled (or confirmed no-op/N-A for
    # MO) -- those three files are deleted, this replaces them.
    config.load_defaults(7.2)

    # load_defaults(7.0) sets action_dispatch.cookies_serializer = :json;
    # override back to :hybrid so existing marshal-serialized cookies
    # keep deserializing. Safe to keep on :hybrid long-term until
    # confident every cookie has been converted to JSON.
    config.action_dispatch.cookies_serializer = :hybrid

    # Not part of any load_defaults version tier -- standalone
    # deprecated-behavior flags outside the version-bundle system, so
    # they stay on legacy behavior unless set explicitly here.
    config.active_support.remove_deprecated_time_with_zone_name = true
    # No-op for MO: no request.content_type call sites.
    config.action_dispatch.return_only_request_media_type_on_content_type =
      false
    # No-op for MO: no Digest::UUID.uuid_v3/uuid_v5 call sites.
    config.active_support.use_rfc4122_namespaced_uuids = true

    # Set Time.zone default to the specified zone and
    # make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names.
    # Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from
    # config/locales/*.rb, yml are auto loaded.
    # config.i18n.load_path +=
    #  Dir[Rails.root.join("my", "locales", "*.{rb,yml}").to_s]
    # config.i18n.default_locale = :de
    config.i18n.enforce_available_locales = true

    # Configure sensitive parameters which will be filtered from the log file.
    config.filter_parameters += [:password]

    # Scrub invalid UTF-8 out of every request at the front of the stack,
    # before anything (including Rails' log param-filtering) touches it --
    # else a scanner's malformed bytes reach a String op and 500.
    config.middleware.insert_before(0, Rack::UTF8Sanitizer)

    # A hostile/garbage Accept header (vulnerability scanners) is the
    # client's error, not a 500.
    config.action_dispatch.rescue_responses[
      "ActionDispatch::Http::MimeNegotiation::InvalidType"
    ] = :not_acceptable

    # Tells rails not to generate controller-specific css and js stubs.
    config.generators.assets = false

    # This instructs ActionView how to mark form fields which have an error.
    # I just change the CSS class to "has-error", which gives it a red border.
    # This is superior to the default, which encapsulates the field in a div,
    # because that throws the layout off.  Just changing the border, while less
    # conspicuous, has no effect on the layout.  This is not a hack, this is
    # just a standard configuration many rails apps take advantage of.
    # Note client side validation is not working as of 2023-02-01
    # For bootstrap 4 the class is "is-invalid"
    config.action_view.field_error_proc = proc { |html_tag, _instance|
      html_tag.gsub("form-control", "form-control has-error").html_safe
    }
    # Rails removed automatically generated input IDs in forms generated by
    # `form_with` in 5.1, but then restored them in 5.2. However, the
    # default does not seem to work on MO. This restores automatically
    # generated form input IDs in 6.1, as they were in `form_for`.
    config.action_view.form_with_generates_ids = true

    # Turbo supersedes the functionality offered by Rails UJS to turn links and
    # form submissions into XMLHttpRequests, so if you're making a complete
    # switch from Rails UJS to Turbo, you should ensure that you have this:
    config.action_view.form_with_generates_remote_forms = false
    # This is a UJS config that can be explicitly set
    # config.action_view.automatically_disable_submit_tag = false

    # Rails 6.1 can auto-generate HTML comments with the template filename
    # Unfortunately this is also added to email templates!
    # config.action_view.annotate_rendered_view_with_filenames = true

    # Strict loading - either :log, or :error out the page
    config.active_record.action_on_strict_loading_violation = :log

    # load_defaults(7.2) already sets cache_format_version to 7.1 (MO's
    # single-process stop/start deploy means there's no window where old
    # and new code read the cache at the same time, so this is safe).

    # Opt in to the Rails 8.0 #to_time behavior now (preserves the
    # receiver's timezone offset instead of converting to system local).
    # Not part of load_defaults(7.2) -- an 8.0-era setting adopted early.
    config.active_support.to_time_preserves_timezone = true

    # Set up memcached as the cache store everywhere
    # config.cache_store = :mem_cache_store
    config.cache_store = :solid_cache_store

    config.solid_cache.connects_to = { database: { writing: :cache } }
    # https://github.com/rails/solid_queue?tab=readme-ov-file#other-configuration-settings
    config.solid_queue.clear_finished_jobs_after = 1.week

    # dartsass-sprockets - sssh! about the bootstrap deprectations
    config.sass.quiet_deps = true
    config.sass.silence_deprecations = ["import"]
  end
end

MO = MushroomObserver::Application.config
require_relative("consts")
