#!/bin/bash

# Database backups not guaranteed to exist yet for today's date.
# Note this uses MacOSX syntax, for local use only.
yesterdays_date=$(date -v -1d '+%Y%m%d')

# Prompt the user for their name
read -p "Please enter your account name on the images server: " user_name

scp "$user_name@images.mushroomobserver.org:/data/images/backup/database-$yesterdays_date.gz" ./checkpoint.gz
