#!/bin/bash

mysql -u mo -p mo_development <<EOB
source checkpoint;
update users set password = 'ae98587c6f1599fbdcc800e66db6874a8fa0e713';
update users set email = 'user@localhost.localdomain';
delete from draft_names;
delete from past_draft_names;
delete from projects;
delete from queued_email_integers;
delete from queued_email_notes;
delete from queued_email_strings;
delete from queued_emails;
delete from search_states;
delete from sequence_states;
quit
EOB

mysqldump -u mo -p mo_development > checkpoint_stripped
bzip2 -f checkpoint_stripped
