#!/bin/bash

ls /var/web/mushroom-observer/public/images/thumb | sort -n | tail -1
mysqldump -u mo -p mo_production | gzip -c - > checkpoint.gz
ls /var/web/mushroom-observer/public/images/thumb | sort -n | tail -1
chmod 640 checkpoint.gz
