#!/bin/bash
#
#  Script run when no-reply user gets an email.
#
################################################################################
set -e

source $(dirname "$0")/bash_include

subject=$1

tempfile="/tmp/autoreply.$$"
autoreply="/home/$USER/.autoreply"

if (( $testing )); then
  autoreply=$app_root/test/reports/autoreply
fi

cat $autoreply | sed "/^Subject:/,+1d" > $tempfile
echo >> $tempfile
echo "----------------------------------------" >> $tempfile
echo >> $tempfile
sed '1,/^ *$/d' >> $tempfile

send_mail -s "$subject" $SENDER < $tempfile
rm -f $tempfile

exit 0
