#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative("../config/boot")
require_relative("../config/environment")

LocationDescription.
  find_each { |x| puts "LocationDescription #{x.id} #{x.source_type.inspect}" }
NameDescription.find_each do |x|
  puts "NameDescription #{x.id} #{x.review_status.inspect}"
  puts "NameDescription #{x.id} #{x.source_type.inspect}"
end
Name.find_each { |x| puts "Name #{x.id} #{x.rank.inspect}" }
Name::Version.find_each { |x| puts "Name::Version #{x.id} #{x.rank.inspect}" }
Query.find_each { |x| puts "Query #{x.id} #{x.model_symbol.inspect}" }
User.find_each do |x|
  puts "User #{x.id} #{x.thumbnail_size.inspect}"
  puts "User #{x.id} #{x.image_size.inspect}"
  puts "User #{x.id} #{x.votes_anonymous.inspect}"
  puts "User #{x.id} #{x.location_format.inspect}"
  puts "User #{x.id} #{x.hide_authors.inspect}"
  puts "User #{x.id} #{x.keep_filenames.inspect}"
end
