#!/bin/bash
set -e
source $(dirname "$0")/bash_include
run_mysql "SELECT id, thumb_image_id, 'thumbnail image doesnt exist' \
           FROM observations WHERE \
           thumb_image_id IS NOT NULL AND \
           thumb_image_id NOT IN \
           (SELECT DISTINCT image_id FROM images_observations)" | grep -v thumb
