#!/bin/sh
# Originally from: # http://sylvana.net/jpegcrop/exif_orientation.html
# Significantly rewritten by Jason Hollinger 2020-03-22.

for file
do
  # Get value of the orientation tag.
  orientation=`exiftool -n -Orientation "$file" | sed "s/.*: //"`

  # Try clearing the orientation tag; if this fails, try fixing the EXIF header
  # and doing it again.
  exiftool -overwrite_original -Orientation=1 "$file" || \
    exiftool -overwrite_original -all= -tagsfromfile @ -all:all -unsafe -icc_profile "$file" && \
    exiftool -overwrite_original -Orientation=1 "$file"

  case $orientation in
  1) transform="";;
  2) transform="-flip horizontal";;
  3) transform="-rotate 180";;
  4) transform="-flip vertical";;
  5) transform="-transpose";;
  6) transform="-rotate 90";;
  7) transform="-transverse";;
  8) transform="-rotate 270";;
  *) transform="";;
  esac

  if test -n "$transform"; then
    convert $transform $file tempfile.jpg
    if test $? -ne 0; then
      echo Error while transforming $file - skipped.
    else
      mv -f tempfile.jpg "$file"
    fi
  fi
done
