#!/usr/bin/env ruby

require File.expand_path('../../config/boot.rb', __FILE__)
require File.expand_path('../../config/environment.rb', __FILE__)

fixed = 0
for naming in Naming.all
  hash = naming.reasons
  if hash.is_a?(Hash)
    any = false
    for key, value in hash
      if value.is_a?(String)
        begin
          value.match(/.*/)
        rescue
          puts "#{naming.id}: #{value.inspect}"
          any = true
        end
      end
    end
    fixed += 1 if any
  end
end
puts "found #{fixed} corrupt namings"
puts "total of #{Naming.count} namings"
