#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates one CHANGELOG.md section per production deploy (issue
# #5155): a dated heading for a deploy-* tag with a flat list of every
# PR merged since the previous deploy tag. PR titles/authors/urls come
# from the gh CLI (run it wherever gh is authenticated); the PR list
# comes from the merge commits between the two tags.
#
#   Dry run (default -- prints the section, writes nothing):
#     script/generate_changelog.rb              # most recent deploy tag
#     script/generate_changelog.rb --tag deploy-2026-08-18-15-03
#   Apply (inserts the section into CHANGELOG.md, newest first):
#     script/generate_changelog.rb [--tag TAG] --apply
#
# Idempotent: --apply refuses to insert a section whose deploy tag is
# already present. Standalone by design -- the deploy.sh hook comes
# later, once the format has settled.

require("json")
require("open3")

# Builds and inserts one deploy's CHANGELOG.md section.
class ChangelogGenerator
  CHANGELOG = "CHANGELOG.md"
  TAG_PATTERN = /\Adeploy-(\d{4}-\d{2}-\d{2})-\d{2}-\d{2}\z/
  USAGE = "Usage: script/generate_changelog.rb [--tag DEPLOY_TAG] " \
          "[--apply]"
  HEADER = <<~MD
    # Changelog

    One section per production deploy, newest first, listing every
    merged PR. Generated by `script/generate_changelog.rb` (issue
    #5155). The user-facing changelog is the [MO improvements
    article](https://mushroomobserver.org/articles/55).
  MD

  def initialize(argv)
    @apply = false
    @tag = nil
    parse_args(argv)
  end

  def run
    tags = deploy_tags
    target = @tag || tags.last
    abort("No deploy-* tags found.") unless target
    index = tags.index(target) ||
            abort("#{target} is not a deploy-* tag (git fetch --tags?).")
    abort("#{target} is the earliest deploy tag; no range.") if index.zero?

    section = build_section(target, merged_prs(tags[index - 1], target))
    @apply ? apply(section, target) : dry_run(section)
  end

  private

  def parse_args(argv)
    args = argv.dup
    until args.empty?
      case (arg = args.shift)
      when "--apply" then @apply = true
      when "--tag" then @tag = args.shift || abort(USAGE)
      else abort("Unknown argument: #{arg}\n#{USAGE}")
      end
    end
  end

  # Zero-padded date-stamped names, so name order is date order.
  def deploy_tags
    run_cmd("git", "tag", "-l", "deploy-*").split("\n").
      grep(TAG_PATTERN).sort
  end

  # git log lists newest first; reverse to merge order.
  def merged_prs(prev_tag, target_tag)
    run_cmd("git", "log", "--merges", "--format=%s",
            "#{prev_tag}..#{target_tag}").
      split("\n").
      filter_map { |subject| subject[/\AMerge pull request #(\d+)/, 1] }.
      reverse.
      map { |number| pr_info(number) }
  end

  def pr_info(number)
    JSON.parse(
      run_cmd("gh", "pr", "view", number,
              "--json", "number,title,url,author")
    )
  end

  def build_section(tag, prs)
    lines = ["## #{tag[TAG_PATTERN, 1]} (#{tag})", ""]
    lines += if prs.empty?
               ["(no merged PRs -- asset-only or config deploy)"]
             else
               prs.map { |info| pr_line(info) }
             end
    "#{lines.join("\n")}\n"
  end

  def pr_line(info)
    "- #{info["title"]} ([##{info["number"]}](#{info["url"]}), " \
      "@#{info.dig("author", "login")})"
  end

  def dry_run(section)
    puts(section)
    warn("Dry run - nothing written. To apply: " \
         "script/generate_changelog.rb#{" --tag #{@tag}" if @tag} --apply")
  end

  def apply(section, tag)
    content = File.exist?(CHANGELOG) ? File.read(CHANGELOG) : HEADER
    if content.include?("(#{tag})")
      abort("CHANGELOG.md already has a section for #{tag}.")
    end

    File.write(CHANGELOG, insert_sorted(content, section, tag))
    warn("Inserted #{tag} section into #{CHANGELOG}.")
  end

  # Sections run newest first. Insert above the first existing section
  # older than this tag, so historical tags can be applied in any
  # order; a tag newer than everything lands right under the header,
  # and one older than everything appends at the end.
  def insert_sorted(content, section, tag)
    older = section_positions(content).find { |_pos, t| t < tag }
    if older
      "#{content[0...older[0]]}#{section}\n#{content[older[0]..]}"
    else
      "#{content.chomp}\n\n#{section}"
    end
  end

  # [offset, deploy-tag] for each section heading, in file order.
  def section_positions(content)
    positions = []
    content.scan(/^## \d{4}-\d{2}-\d{2} \((deploy-[0-9-]+)\)/) do
      positions << [Regexp.last_match.begin(0), Regexp.last_match[1]]
    end
    positions
  end

  def run_cmd(*cmd)
    out, err, status = Open3.capture3(*cmd)
    abort("`#{cmd.join(" ")}` failed:\n#{err}") unless status.success?
    out
  end
end

ChangelogGenerator.new(ARGV).run
