#!/usr/bin/env ruby
# frozen_string_literal: true

#
#  USAGE::
#
#    script/jobs_cleanup
#
#  DESCRIPTION::
#
#  Build robots.txt, a set of sitemap.xml files, and a set of pared-down
#  index.html files for robots to use to index our site efficiently.

require_relative("../config/boot")
require_relative("../config/environment")
require("mission_control-jobs")

# connect to mission_control
connect_to mushroomobserver

count = ActiveJobs.jobs.failed.count
if count.positive?
  discard_date = 5.months.ago.in_time_zone("UTC")
  ActiveJob.jobs.failed.each do |job|
    job.discard if job.failed_at < discard_date
  end
  discarded = count - ActiveJobs.jobs.failed.count
  puts("Discarded #{discarded} jobs which failed before #{discard_date}")
end

# DELETE ME
