#!/usr/bin/env ruby
# frozen_string_literal: true

require("fastimage")
require("stringio")
#
#  Uses FastImage gem to read width and height of JPEG image from header.
#  We could use ImageMagick identify to do the same thing. This script was
#  originally written because ImageMagick loaded the entire image into memory.
#  That is no longer true, but gem is probably faster and used for consistency.
#
################################################################################

# ------------------------------------
#  Grab dimensions from JPEG header.
# ------------------------------------

# ----------------------------
#  Main program.
# ----------------------------

case ARGV[0]

# Help message
when "-h", "--help"
# Fall through to display help.

# Given file of files.
when "-f", "--file"
  file = ARGV[1]
  any = false
  File.readlines(file).each do |line|
    file2 = line.chomp
    w, h = FastImage.size(file2)
    if w
      $stdout.puts("#{file2}: #{w} #{h}")
      any = true
    end
  end
  exit(any ? 0 : 1)

# Just given single filename.
else
  if (ARGV.length == 1) && !ARGV[0].start_with?("-")
    file = ARGV[0]
    w, h = FastImage.size(file)
    if w
      $stdout.puts("#{w} #{h}")
      exit(0)
    else
      exit(1)
    end
  end
end

# Help message whenever screw up command line.
warn(%(
  USAGE
    script/jpegsize <file>.jpg
    script/jpegsize -f <file_list.txt>

  DESCRIPTION
    Reports the size of one or more JPEG files.

  OPTIONS
    -h --help             Print this message.
    -f --file <file>      Report size of all files listed in <file>.

))

exit(1)
