#!/bin/bash
#
#  USAGE::
#
#    script/lookup_user <search_string>
#
#  DESCRIPTION::
#
#  Lookup all users with login, name or email containing the given string.
#
################################################################################
set -e

source $(dirname "$0")/bash_include

(
  echo -e "id\tlogin\tname\temail\tverified\tlast_use" &&
  run_mysql "
    SELECT id, login, name, email, verified,
           IF(last_activity, last_activity, last_login)
      FROM users
     WHERE id='$1' AND id != 0 OR login LIKE '%$1%' OR
           name LIKE '%$1%' or email LIKE '%$1%'
  "
) | column -t -s $'\t'
