#!/usr/bin/env ruby
#
#  USAGE::
#
#    script/makexml
#
#  DESCRIPTION::
#
#  Puts the contents of name/eol into a file called eol.xml
#
################################################################################

# URL = "http://mushroomobserver.org/name/eol"
URL = "http://localhost:3000/name/eol"

# Prime the pump both to get around Jason's JavaScript detector
# and to get the SQL caches loaded
cmd = "wget -O /dev/null '#{URL % 0}'"
system cmd

last_name = false

cmd = "wget -O eol.xml '#{URL}'"
system cmd
