#!/bin/sh
grep '^[A-Za-z:]*Error \|ENOMEM' /var/web/mushroom-observer/log/production.log | grep -v 'ActionController::RoutingError' | grep -v 'ActiveRecord::RecordNotFound' > /var/web/mushroom-observer/log/errors.new
touch /var/web/mushroom-observer/log/errors.old
diff /var/web/mushroom-observer/log/errors.new /var/web/mushroom-observer/log/errors.old
mv /var/web/mushroom-observer/log/errors.new /var/web/mushroom-observer/log/errors.old
