#!/bin/bash
#
#  USAGE::
#
#    script/parse_log
#
#  DESCRIPTION::
#
#  Grabs all the error messages from the server log file, and outputs any new
#  ones since last time this was run.
#
################################################################################
set -e

source $(dirname $0)/bash_include

rails_log=$app_root/log/$RAILS_ENV.log
old_errors=$app_root/log/errors.old
new_errors=$app_root/log/errors.new

grep 'FATAL.* [A-Za-z:]*Error \|ENOMEM' $rails_log |
grep -v 'Using a password on the command line' |
grep -v 'Can.t figure out how to sort' |
grep -v 'ActionController::RoutingError' |
grep -v 'ActiveRecord::RecordNotFound' |
grep -v 'Rack::QueryParser::InvalidParameterError' |
grep -v 'ActionView::Template::Error .Character not in alphabet' \
  > $new_errors || true

touch $old_errors
diff $new_errors $old_errors || true
mv $new_errors $old_errors

exit 0
