#!/bin/sh
grep :: /var/web/mo/log/production.log | grep -v 'ActionController::RoutingError' | grep -v 'ActiveRecord::RecordNotFound' > /var/web/mo/log/errors.new
touch /var/web/mo/log/errors.old
diff /var/web/mo/log/errors.new /var/web/mo/log/errors.old
mv /var/web/mo/log/errors.new /var/web/mo/log/errors.old
