#!/usr/bin/env python

import time, os, sys

(cmd, site, imgPath, logPath) = sys.argv

timeFormat = '%Y-%m-%d.%H.%M.%S'
logDir = logPath + '/' + time.strftime(timeFormat)

os.makedirs(logDir + '/observer')
os.makedirs(logDir + '/image')

logFile = open(logPath + '/perf.log', 'a')

def runCurl(page, arg=None, img=None):
  logFile.write("%s:%s: " % (page, time.strftime(timeFormat)))
  cmd = "curl"
  if img:
    if os.path.isfile(img):
      cmd += ' -F "file=@%s"' % img
    else:
      print "Unable to find the image file: %s" % img
      logFile.write("ERROR\n")
      return
  url = "http://%s/%s" % (site, page)
  if arg:
    url += "/%s" % arg
  url += "\?_js=on\&_new=true"
  cmd += " %s -o %s/%s -s -i" % (url, logDir, page)
  start = time.time()
  os.system(cmd)
  logFile.write("%s\n" % (time.time() - start))

runCurl('observer/list_rss_logs')
runCurl('image/show_image', 35165)
runCurl('observer/show_observation', 17430)
runCurl('image/test_upload_speed', img=imgPath)

logFile.close()
