#!/usr/bin/env ruby
# frozen_string_literal: true

# This command will automatically be run when you run "rails"
# with Rails 3 gems installed from the root of your application.

APP_PATH = File.expand_path("../config/application", __dir__)
require_relative("../config/boot")
require("rails/commands")
