#!/usr/bin/env bash
#
#  Re-transfer any images that haven't transferred correctly yet.
#
################################################################################
set -e

source $(dirname "$0")/bash_include
source $(dirname "$0")/bash_images

if [[ $1 == "-h" || $1 == "--help" ]]; then cat <<END; exit 1; fi

USAGE
  script/retransfer_images

DESCRIPTION
  This is used by the webserver to try to re-transfer images which failed to
  transfer when script/process_image ran.  It sets the "transferred" bit in
  the images database table if successful.  It aborts at the first sign of
  any trouble.

END

ids=$( run_mysql "SELECT id FROM images WHERE transferred=FALSE" )

for id in $ids; do
  for subdir in thumb 320 640 960 1280 orig; do
    for file in $(cd $image_root && ls $subdir/$id.* 2> /dev/null); do
      for server in ${image_servers[@]}; do
        if image_server_has_subdir $server $subdir; then
          copy_file_to_server $server $file
        fi
      done
    done
  done

  run_mysql "UPDATE images SET transferred=TRUE WHERE id=$id" &&
  run_mysql "UPDATE observations, observation_images SET observations.updated_at = NOW() WHERE observation_images.image_id = $id AND observation_images.observation_id = observations.id" || \
    die "Failed to set transferred bit on $id."
done

exit 0
