#!/bin/bash
#
#  Re-transfer any images that haven't transferred correctly yet.
#
################################################################################
set -e

source $(dirname "$0")/bash_include

images_root=$( rails_constant LOCAL_IMAGE_FILES )

if [[ $1 == "-h" || $1 == "--help" ]]; then cat <<END; exit 1; fi

USAGE
  script/retransfer_images

DESCRIPTION
  This is used by the webserver to try to re-transfer images which failed to
  transfer when script/process_image ran.  It sets the "transferred" bit in
  the images database table if successful.  It aborts at the first sign of
  any trouble.

END

# Get list of images that still need to go.
ids=$( run_mysql "SELECT id FROM images WHERE transferred=FALSE" )
[[ $ids = "" ]] && exit 0

# Transfer images.
for id in $ids; do
  # Assume verify_images has done our job for us if any files are missing.
  for dir in {thumb,320,640,960,1280,orig}; do
    for file in $images_root/$dir/$id.*; do
      if [[ -e $file ]]; then
        wait_for scp
        for server in ${image_servers[@]}; do
          scp $file $server/$dir/ || die "Failed to transfer $file to $server/$dir/."
        done
      fi
    done
  done

  # Update database to say that image has transferred successfully.
  run_mysql "UPDATE images SET transferred=TRUE WHERE id=$id" || warn "Failed to set transferred bit on $id."
done

exit 0
