#!/bin/bash

source $(ls /usr/local/rvm/environments/ruby-1.9.3-p* | grep -v @ | tail -1)

dir=$(dirname "$0")
if [[ $2 == '-v' ]]; then
  echo Running $dir/$*
fi
$dir/$* 2>&1 | grep -v "29: warning: nested"
