#!/bin/bash

ruby_version=$(cat /var/web/mushroom-observer/.ruby-version)
source /usr/local/rvm/environments/ruby-$ruby_version

rake $* -f /var/web/mushroom-observer/Rakefile | \
  grep -v '(in /home/' | grep -v '^\*\* '
