#!/bin/bash

if [[ $RAKE_TEST_LOADER != '' ]]; then
  loader=$RAKE_TEST_LOADER
elif [[ $MY_RUBY_HOME != '' ]]; then
  loader=$MY_RUBY_HOME/lib/ruby/1.9.1/rake/rake_test_loader.rb
else
  loader=/usr/local/lib/ruby/1.9.3/rake/rake_test_loader.rb
fi

echo
echo Preparing database using old mysql adapter...
perl -pi -e 's/ mysql2$/ mysql/; $_' config/database.yml
rake db:test:prepare
perl -pi -e 's/ mysql$/ mysql2/; $_' config/database.yml

echo
echo Running tests using new mysql2 adapter...
ruby -Ilib:test $loader test/{unit,functional,integration}/*_test.rb
