#!/bin/bash
set -e

RAILS_ENV=production

rvm_env=$(ls /usr/local/rvm/environments/ruby-1.9.3-p* | grep -v @ | tail -1)

app_root=/var/web/mushroom-observer
pid_file=$app_root/tmp/unicorn.pid
conf_file=$app_root/config/unicorn.rb

case "$1" in
start)
  if [ -s $pid_file ]; then
    echo "Unicorn already running."
    exit 1
  else
    echo "Starting unicorn..."
    cd $app_root
    sudo -u mo "source $rvm_env && bundle exec unicorn_rails -c $conf_file -D" && exit 0
    echo "FAILED!"
    exit 1
  fi
  ;;
stop)
  if [ ! -s $pid_file ]; then
    echo "Unicorn not running."
    exit 1
  else
    echo "Stopping unicorn..."
    kill -QUIT `cat $pid_file` && exit 0
    echo "FAILED!"
    exit 1
  fi
  ;;
restart)
  if [ ! -s $pid_file ]; then
    echo "Unicorn not running."
    exit 1
  else
    echo "Restarting unicorn..."
    old_pid=`cat $pid_file`
    rm $pid_file
    kill -s USR2 $old_pid
    sleep 5
    # wait up to a minute for new unicorn to start
    for x in 1 2 3 4 5 6 7 8 9 10 11 12; do
      test -s $pid_file || sleep 5
    done
    if [ ! -s $pid_file ]; then
      echo "FAILED! Old pid was $old_pid."
      echo $old_pid > $pid_file
      exit 1
    else
      kill -9 $old_pid
      exit 0
    fi
  fi
  ;;
reload)
  if [ ! -s $pid_file ]; then
    echo "Unicorn not running."
    exit 1
  else
    echo "Reloading unicorn workers..."
    kill -HUP `cat $pid_file` && exit 0
    echo "FAILED!"
    exit 1
  fi
  ;;
status)
  if [ ! -s $pid_file ]; then
    echo "Unicorn not running."
    exit 1
  else
    pid=`cat $pid_file`
    echo "Unicorn running as $pid."
    exit 0
  fi
  ;;
*)
  echo "Usage: $0 {start|stop|restart|reload|status}"
  exit 1
  ;;
esac
