#!/usr/bin/env ruby

require 'digest/md5'
require 'net/http'
require 'uri'

# HOST = 'localhost'
# PORT = 3000
HOST = 'localhost.localdomain'
PORT = 80

# Net::HTTP.get_print(URI.parse("http://#{HOST}:#{PORT}/observer/how_to_help"))
# exit

# Net::HTTP.get_print(HOST, '/observer/how_to_help', PORT)
# exit

# http = Net::HTTP.new(HOST, PORT)
# response = http.get('/api/images?id=3')
# puts response.body
# exit

http = Net::HTTP.new(HOST, PORT)
path = '/api/images?' + [
  'date=20100102',
  'notes=blah%20blah',
  'api_key=tt7udys2zlp5f0fwj27blduraxgkdy329',
].join('&')
data = File.open('test/fixtures/images/sticky.jpg', 'rb') {|fh| fh.read}
head = {
  'Content-Type' => 'image/jpeg',
  'Content-Length' => data.length.to_s,
  'Content-MD5' => Digest::MD5.hexdigest(data),
}
response = http.post(path, data, head)
puts response.body
exit

# http = Net::HTTP.new(HOST, PORT)
# path = '/api/images?' + [
#   'date=20100102',
#   'notes=blah%20blah',
#   'auth_id=252',
#   'auth_code=dd772e209cd40bd07c0b6535abf00b08d41712b3',
#   'url=' + HOST + '/images/thumb/1.jpg'
# ].join('&')
# response = http.post(path, nil)
# puts response.body

# http = Net::HTTP.new(HOST, PORT)
# path = '/api/images?' + [
#   'date=20100102',
#   'notes=blah%20blah',
#   'auth_id=252',
#   'auth_code=dd772e209cd40bd07c0b6535abf00b08d41712b3',
#   'file=test.jpg'
# ].join('&')
# response = http.post(path, nil)
# puts response.body

