#!/usr/bin/env ruby

require "digest/md5"
require "net/http"
require "net/https"
require "uri"

# HOST = 'mushroomobserver.org'
# PORT = 443
HOST = "localhost".freeze
PORT = 3000
KEY = "xxx".freeze

################################################################################

# # Get observation #1.
# http = Net::HTTP.new(HOST, PORT)
# http.use_ssl = true if PORT == 443
# response = http.get('/api/observations?id=1')
# puts response.body
# exit

# Create observation.
http = Net::HTTP.new(HOST, PORT)
http.use_ssl = true if PORT == 443
path = "/api/observations?" + [
  "api_key=" + KEY,
  "help=1"
].join("&")
response = http.post(path, "")
puts response.body
exit

# # Create image via upload.
# http = Net::HTTP.new(HOST, PORT)
# http.use_ssl = true if PORT == 443
# path = '/api/images?' + [
#   'date=20100102',
#   'notes=blah%20blah',
#   'api_key=' + KEY,
# ].join('&')
# data = File.open('test/images/Coprinus_comatus.jpg', 'rb') {|fh| fh.read}
# head = {
#   'Content-Type' => 'image/jpeg',
#   'Content-Length' => data.length.to_s,
#   'Content-MD5' => Digest::MD5.hexdigest(data),
# }
# response = http.post(path, data, head)
# puts response.body
# exit

# # Create image via url.
# http = Net::HTTP.new(HOST, PORT)
# http.use_ssl = true if PORT == 443
# path = '/api/images?' + [
#   'date=20100102',
#   'notes=blah%20blah',
#   'auth_id=252',
#   'auth_code=dd772e209cd40bd07c0b6535abf00b08d41712b3',
#   'url=' + HOST + '/images/thumb/1.jpg'
# ].join('&')
# response = http.post(path, nil)
# puts response.body

# # Create image via local file (admin would have to upload to server first).
# http = Net::HTTP.new(HOST, PORT)
# http.use_ssl = true if PORT == 443
# path = '/api/images?' + [
#   'date=20100102',
#   'notes=blah%20blah',
#   'auth_id=252',
#   'auth_code=dd772e209cd40bd07c0b6535abf00b08d41712b3',
#   'file=test.jpg'
# ].join('&')
# response = http.post(path, nil)
# puts response.body
