#!/usr/bin/env ruby

require File.expand_path("../config", __FILE__)

require "digest/md5"
require "net/http"
require "net/https"
require "uri"
require "json"

https = Net::HTTP.new(MO.pivotal_url, 443)
headers = { "X-TrackerToken" => MO.pivotal_token }
https.use_ssl = true

path = "#{MO.pivotal_path}/projects/#{MO.pivotal_project}/stories?limit=1000"
req = Net::HTTP::Get.new(path, headers)
res = https.request(req)

stories = JSON.parse(res.body).map do |story|
  data = {
    :labels   => [],
    :comments => [],
  }
  data[:id]       = story["id"]
  data[:type]     = story["story_type"]
  data[:time]     = story["created_at"]
  data[:state]    = story["current_state"]
  data[:name]     = story["name"]
  data[:desc]     = story["description"]
  data[:labels]   = story["labels"].map {|l| l["name"]}
  puts data.inspect
  puts "-"*80
  data
end
puts "Found #{stories.length} stories!"

exit 0
