#!/bin/bash

mysql -u mo -pmo mo_development -e ''
if [ ! $? -eq 0 ]; then
    mysql -u root < db/initialize.sql
    echo Created databases
else
    echo mo_development exists
fi

if [ ! -f config/database.yml ]; then
    cp db/vagrant/database.yml config
    echo Copied config/database.yml
    cat config/database.yml
else
    echo database.yml exists
fi

for dir in images test_images;
do
    for subdir in thumb 320 640 960 1280 orig;
    do
	if [ ! -d public/$dir/$subdir ]; then
	    mkdir -p public/$dir/$subdir
	    echo Created public/$dir/$subdir
	else
	    echo public/$dir/$subdir exists
	fi
    done
done

if [ ! -f /usr/local/bin/jpegresize ]; then
    sudo gcc script/jpegresize.c -ljpeg -lm -O2 -o /usr/local/bin/jpegresize
    echo Created and installed jpegresize executable
else
    echo jpegresize exists
fi

if [ ! -f /usr/local/bin/jpegexiforient ]; then
    sudo gcc script/jpegexiforient.c -o /usr/local/bin/jpegexiforient
    echo Created and installed jpegexiforient executable
else
    echo jpegexiforient exists
fi

if [ ! -f /usr/local/bin/exifautotran ]; then
    sudo cp script/exifautotran /usr/local/bin/exifautotran
    sudo chmod 755 /usr/local/bin/exifautotran
    echo Installed exifautotran script
else
    echo exifautotran exists
fi

git pull
gem install bundler
bundle install
