#!/usr/bin/bash
# Run as user with sudo power

DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt -y install zsh

username=mo

# Prompts user for password
if getent passwd "$username" > /dev/null 2>&1; then
    echo "User '$username' already exists"
else
    useradd -m -G sudo -s /bin/zsh "$username"
    passwd "$username"
    echo "Successfully created user '$username'"
fi

user_home=$(getent passwd "$username" | cut -d: -f6)
zshrc_path="$user_home/.zshrc"
if [ ! -f "$zshrc_path" ]; then
    cat > "$zshrc_path" << EOF
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/$username/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
EOF
    chown "$username:$username" "$zshrc_path"
    chmod 644 "$zshrc_path"
    echo "Successfully initialized .zshrc for user '$username'"
else
    echo "$zshrc_path already exists"
fi

ssh_dir="$user_home/.ssh"
if [ ! -e "$ssh_dir" ]; then
    mkdir "$ssh_dir"
    cp ~/.ssh/authorized_keys >> "$ssh_dir/authorized_keys"
    chmod 700 "$ssh_dir"
    chown -R "$username:$username" "$ssh_dir"
    echo "Successfully setup SSH for user '$username'"
else
    echo "$ssh_dir already exists"
fi

if [ ! -e /var/web ]; then
    mkdir /var/web
    chmod 777 /var/web
    echo Created /var/web
else
    echo /var/web already exists
fi

apt update
DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt -y upgrade
DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt -y install \
tcsh zsh man vim lynx telnet emacs wget build-essential \
bison libyaml-dev libxslt-dev mysql-server mysql-client \
libmysqlclient-dev libcurl4-openssl-dev libssl-dev libapr1-dev \
libaprutil1-dev libreadline-dev zlib1g-dev imagemagick \
libmagickcore-dev libmagickwand-dev libjpeg-dev libjpeg-progs \
libimage-exiftool-perl

cd /tmp
rm -rf build
mkdir build

# Install chruby
if [ ! -f /usr/local/share/chruby/chruby.sh ]; then
    echo chruby needs to be installed
    cd build
    wget https://github.com/postmodern/chruby/archive/master.tar.gz
    tar -xzvf master.tar.gz
    rm master.tar.gz
    cd chruby-master
    sudo make install
    cd ../..
    echo "source /usr/local/share/chruby/chruby.sh" >> ~/.zshrc
    echo "source /usr/local/share/chruby/auto.sh" >> ~/.zshrc
    echo Installed chruby
else
    echo chruby install skipped: /usr/local/share/chruby/chruby.sh exists
fi

# Install ruby-install
which ruby-install
if [ ! $? -eq 0 ]; then
    echo ruby-install needs to be installed
    cd build
    wget https://github.com/postmodern/ruby-install/archive/master.tar.gz
    tar -xzvf master.tar.gz
    cd ruby-install-master
    sudo make install
    cd ../..
    ruby-install ruby `cat .ruby-version`
    echo Install ruby-install
else
    echo ruby-install already installed, skipping
fi

rm -rf build
